### ISSUE TITLE
Time required to flush cache

### ISSUE THREAD

**Issue by tomhartley** [m8pple/arch2-2015-cw2#3]
For flushing the cache, I think that the time required is at least WRITE_TIME \* (number of dirty blocks).

However, to check if each block is dirty we have to hit the cache (assuming we didn't store this elsewhere in a separate area of memory). Do we also include (HIT_TIME) \* (number of blocks we check for dirtiness) in the time to flush?

Thank you.

**Comment by m8pple** [comment]
A reasonable question, but I think it is approaching it from a more software,
or sequential, point of view. So I agree that you need to scale the write time
by the number of dirty blocks. However:

In terms of the time taken to search for the dirty blocks, in software that
would be proportional to the number of blocks. But in hardware, we could
implement parallel checking - for example, it would be possible to use a
combinational leading-one-detector (or encoder) to find the first dirty
block. This would have logarithmic critical path, but wouldn't need to
be linear time. So, with some energetic (if not frantic) hand-waving, it
could be claimed that it takes zero time to find the next dirty block to be
flushed to memory, so the only bottleneck is the memory writes.

Supporting this (rather unrealistic) assumption, the relevant part of the spec is this:

```
Flushes do not include the hit time, and only consume the time taken to write dirty pages to memory.
```

So I'm afraid this is a situation where reality is too complicated, and I've just
abstracted away from reality in the interests of keeping the coursework simple.

I'm assuming/hoping you already saw that clause in the spec, so is it that it has
multiple interpretations, or it is ambiguous in a way I didn't anticipate?

**Comment by tomhartley** [comment]
I did indeed see that - but only after posting this issue [whoops]. I decided to leave it up as I was interested in the hardware/decisions behind such a feature. Thank you for delivering on that implicit request!
